### ISSUE TITLE
buftabs-maxlength reintroduction

### ISSUE THREAD

**Issue by trapd00r** [amzyang/buftabs#1]
After updating buftabs, it's no longer possible to make use of the buftabs-maxlength option. I see the code handling it was removed; I wish to have it back.

To me, it makes no sense having every tabname span an arbitary length of characters of space.

**Comment by amzyang** [comment]
hello, you can use css instead.

for example:

hi -a BufTab max-width:200px; " equals to the old 'buftabs-maxlength' option

hi -a BufTab text-overflow:ellipsis " firefox 7.0 or above, buftabs-morestring
