### ISSUE TITLE
Error on start, tab styling fails to load.

### ISSUE THREAD

**Issue by lwatsondev** [amzyang/buftabs#10]
Sourcing file: resource://dactyl/base.jsm:247: TypeError: match is null

Using Pentadactyl 1.1.

**Comment by hello-code** [comment]
Me too!
Pentadactyl 1.1
Debian 8 + Iceweasel 31.8.0
When I open iceweasel show `Sourcing file: resource://dactyl/base.jsm:247: TypeError: match is null`

**Comment by amzyang** [comment]
hello:
Please using nightly pentadactyl build, it works for me.

**Comment by hello-code** [comment]
OK !
Thanks grassofhust !
