### ISSUE TITLE
Favicon support broken

### ISSUE THREAD

**Issue by behrmann** [amzyang/buftabs#4]
With FF10 Icon support seems to be broken. For a while now I had a problem with line 224
image = DEFAULT_FAVICON;
which did not seem to work for me for quite some time. I just changed it to show some other small icon from firefox chrome, which worked. Like
image = "chrome://browser/skin/tabbrowser/tab.png";

With FF10 my version of buftabs completely broke, so I pulled the latest zipball, which did work, but unfortunately on every startup pentadactyl throws "DEFAULT_FAVICON not defined" even when I change the appropriate line to something else (like the new default favicon). This is an issue, since when the default favicon is not properly set, buftabs show NaN for all tabnumbers after a tab, that wants to use the default favicon.

**Comment by amzyang** [comment]
Hello, I've updated buftabs.

If this issue still exists, try :rehash first.

**Comment by behrmann** [comment]
The described issue is fixed, thanks.

I also noticed, that with the two most recent buftabs versions favicons seem to be bigger. They used to have a border of about one pixel, which they now lack. Being bigger, they look far less sharp and have a blurry feel. Is this intentional and if so, is there a way to change it?

**Comment by amzyang** [comment]
Can you show me a screenshot? This may be much clear.

Thanks!

**Comment by behrmann** [comment]
I'd have a screenshot now. Is there any other way to post an image, than to put it into a git?

**Comment by amzyang** [comment]
http://daringfireball.net/projects/markdown/syntax#img

You can upload it to a public image sharing service, then put the link here.

**Comment by behrmann** [comment]
the upper version is buftabs in ff9 the lower version is buftabs in ff10, which looks a bit crammed and the favicons less sharp.

![buftabs ff9 to ff10](http://fenvar.lima-city.de/Drako/buftabs_ff9-10.png)

**Comment by amzyang** [comment]
It seems that the buftabs widget now have the full statusbar height in ff10.

This may be a specific issue with your colorscheme.

**Comment by behrmann** [comment]
My colorscheme is the default one. So, how can does one shrink the widget size back to the original size?

**Comment by amzyang** [comment]
:hi -a BufTab background-size:contain contain;
:hi -a BufTabSelected background-size:contain contain;
:hi -a BufTabAlternate background-size:contain contain;

or 

:hi -a BufTabs margin:1px 0 !important;

You can change 1px to any other value,

**Comment by behrmann** [comment]
Having tried all combinations of both blocks, i think both together yield the most appealing result. I'd recommend adding 

hi -a BufTab background-size:contain contain
hi -a BufTabSelected background-size:contain contain
hi -a BufTabAlternate background-size:contain contain
hi -a BufTabs margin:1px 0 !important

to the recommended settings in the plugin documentation.

Thank you very much, from my point this issue is closed.
