### ISSUE TITLE
Best way to display remote links

### ISSUE THREAD

**Issue by onny** [amzyang/buftabs#6]
Hey, after setup buftabs in pentadactyl, I was able to align all tabs in the button menubar. Now I would like to ask, what's the best way to display a destination when hover over a link. Because the tabs replace now the position where before the links were shown.
Any Ideas?
Best regards,
oNNy

**Comment by amzyang** [comment]
:style chrome://browser/content/browser.xul statuspanel#statusbar-display {display:block;visibility:visible;}

Hello, you can use the code above, when you hover over a link, it will display the destination on the left bottom corner, just above the Add-on.Bar.

or you can give this extension a try:

https://addons.mozilla.org/en-US/firefox/addon/url-tooltip/?src=api

**Comment by onny** [comment]
Wow that's super awesome. This definitively solved my problem!
I really would like to support your work, are you using Flattr?

**Comment by amzyang** [comment]
I haven't use Flattr before.

My ideas and scripts were all built on pentadactyl and vim, 
you can support pentadactyl, this is the same.

thanks!
