### ISSUE TITLE
Buftabs on most recent Pentadactyl Nightly with Firefox 15

### ISSUE THREAD

**Issue by behrmann** [amzyang/buftabs#8]
Hi,

using the most recent Pentadactyl nightly (2012-09-03), which seems to be the first working with Firefox 15, Buftabs is not working and throws an Error "gbrowser not defined". Since I don't see that gBrowser is defined in Buftabs I suspect it is one of those APIs that Mozilla dropped from Firefox with its newest version. I haven't yet had the time to check this. So ist there a quick fix or will it take more work?

**Comment by amzyang** [comment]
I've just replaced  all the 'gBrowser' with 'window.gBrowser', it works again, but not perfect.
