### ISSUE TITLE
Using the GPG decrypt plugin gives an error in the statusline function

### ISSUE THREAD

**Issue by mrschyte** [amzyang/buftabs#9]
If I decrypt a file using the GPG plugin I get an error that the s:list variable is undefined in the buftabs#statusline function. Checking the s:list variable for existance solves the problem:

```
buftabs.vim:
332 function! buftabs#statusline(...)
333   if !exists("s:list")                                                                                                          
334     return ''
335   endif
336   return s:list
337 endfunction
```

**Comment by amzyang** [comment]
Hello, Did you mean buftabs for vim?

It's not written by me.

**Comment by mrschyte** [comment]
Whoops, sorry :)
